trigger:
  - main
 
pool:
  vmImage: 'ubuntu-latest'
 
variables:
  buildConfiguration: 'Release'
 
steps:

- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false

- task: DockerInstaller@0
  inputs:
    dockerVersion: '17.09.0-ce'
 
  # Build Docker Image
- task: Docker@2
  displayName: 'Build the Docker Image'
  inputs:
      command: 'build'
      Dockerfile: '**/Dockerfile'
      arguments: '-t  dapr:$(Build.BuildNumber)'
- task: ECRPushImage@1
  displayName: Push to Jfrog Artifactory
  inputs:
      awsCredentials: 'AWSServiceConnection'
      regionName: 'us-east-2'
      imageSource: imagename
      sourceImageName: 'dapr'
      sourceImageTag: $(Build.BuildNumber)
      pushTag: $(Build.BuildNumber)
      repositoryName: 'dapr'
- task: ECRPushImage@1
  displayName: Push to Jfrog Artifactory
  inputs:
      awsCredentials: 'AWSServiceConnection'
      regionName: 'us-east-2'
      imageSource: imagename
      sourceImageName: 'dapr'
      sourceImageTag: $(Build.BuildNumber)
      pushTag: latest
      repositoryName: 'dapr'
- task: CmdLine@2
  condition: always()
  displayName: Clearing Build images in agent
  inputs:
    script: |
        docker-compose down
        docker rmi -f dapr:$(Build.BuildNumber)