trigger:
  - main
 
pool:
  vmImage: 'ubuntu-latest'
 
variables:
  buildConfiguration: 'Release'
 
steps:

- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false

- task: DockerInstaller@0
  inputs:
    dockerVersion: '17.09.0-ce'
 
  # Build Docker Image
- task: Docker@2
  displayName: 'Build the Docker Image'
  inputs:
      command: 'build'
      Dockerfile: '**/Dockerfile'
      arguments: '-t  dapr:$(Build.BuildNumber)'